### ISSUE TITLE
No way to send extra headers

### ISSUE THREAD

**Issue by PGrimes** [HyperionGray/trio-websocket#110]
When I connect to my server, I need to include an authorization header.  in `websockets` I do this like this `await websockets.connect(uri, extra_headers=headers, ssl=ssl_context)`.  I don't see a way to do this in trio-websocket.

**Comment by belm0** [comment]
Looks like we need to plumb extra_headers through `open_websocket()` --> `connect_websocket()` --> `WebSocketConnection` to the wsproto `Request` object.

**Comment by mehaase** [comment]
Indeed, this wasn't even possible with the old `wsproto`, but is now possible since #106. Thanks for opening this, @PGrimes. I am making a few updates to the library this week and will aim to include this.

**Comment by mehaase** [comment]
Note on previous commit: `extra_headers` was added to the server-side APIs (`accept()` and `reject()`). So for this ticket, I only need to to implement headers for the client-side APIs.
