### ISSUE TITLE
shutdown lifetime issues

### ISSUE THREAD

**Issue by belm0** [HyperionGray/trio-websocket#13]
See https://github.com/python-trio/pytest-trio/issues/63, where there can be shutdown issues with the trio-websocket server (using a connection after stream is closed).

#3 mentions some design improvements

**Comment by mehaase** [comment]
I'm planning to address the recommendations in #3, and then I'll check if that fixes this issue, too.

**Comment by belm0** [comment]
confirmed that #23 fixes this

**Comment by mehaase** [comment]
Thanks, I'll close this now.
