### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by mgorny** [HyperionGray/trio-websocket#173]
The current release fails tests for me with a lot of:

```
E               AttributeError: 'AsyncGenerator' object has no attribute 'port'
```

FWICS it was fixed in 3b6f4e78204e5f487ca6962374e498805c8b7cba. Could you make a new release including this commit?

**Comment by belm0** [comment]
there haven't been any code changes that affect the runtime, which is why I've delayed making a release

You shouldn't see errors when running tests if you use the pinned dependencies.  For example:

```
git checkout 0.9.2
python3.8 -m venv venv
source venv/bin/activate
pip install -r requirements-dev.txt
make test  # PASSES
```

I'd like to understand what you're trying to do, and what version of Python and dependencies you're using when running the tests.

**Comment by mgorny** [comment]
I'm packaging it for Gentoo. We test against the same versions that are will be used in production, i.e. the newest versions at the time. Otherwise (in general), we can't guarantee that the package still works, as automated testing can't distinguish failures due to incompatible code from failures due to incompatible tests.

**Comment by belm0** [comment]
> We test against the same versions that are will be used in production, i.e. the newest versions at the time. 

It sounds a little strange, since any Python library may specify version constraints on their dependencies.  So in the end, when preparing the environment for a particular Python app, distros must accommodate historical versions of Python packages, in order to satisfy dependencies.

**Comment by mgorny** [comment]
This is a complex problem, and we do our best to keep things working which sometimes involves backporting patches to make packages compatible with newer versions of their dependencies. Believe me, you don't wanna know how painful and ungrateful work this is.

**Comment by mgorny** [comment]
Thank you!
