### ISSUE TITLE
Support for arbitrary Listeners and Streams

### ISSUE THREAD

**Issue by njsmith** [HyperionGray/trio-websocket#2]
Part of the idea of Trio's abstract `Listener` and `Stream` interfaces is to make it easy for protocol libraries to get plugged together with new transport types. It would be great if this library made it possible for websocket servers to use an arbitrary `Listener` (or list of listeners, like `open_tcp_listeners` returns and `serve_listeners` expects), and for clients to use an arbitrary `Stream`.

For example, suppose you want to run a websocket server as a Tor hidden service. Someone could build tor-based `Listener` and `Stream` implementations, and then plug them into this library. Or, suppose you want to run a websocket server that uses Let's Encrypt to get certificates. Someone could build a `Listener` that automatically handles this (via the TLS-ALPN challenge method), and then plug it into this library.

**Comment by mehaase** [comment]
Thanks for all the feedback! I am going to start tackling these issues today.
