### ISSUE TITLE
BrokenStreamError deprecation

### ISSUE THREAD

**Issue by belm0** [HyperionGray/trio-websocket#39]
I'm not sure what's to be done.
  * Having trio-websocket require > Trio 0.8.0 just for this?
  * Stay on BrokenStreamError and let users live with the deprecation warning spam?
  * Select the exception type at runtime based on Trio version?

```
/.../site-packages/trio_websocket/__init__.py:210: TrioDeprecationWarning: trio.BrokenStreamError is deprecated since Trio 0.8.0; use trio.BrokenResourceError instead (https://github.com/python-trio/trio/issues/620)
```

**Comment by mehaase** [comment]
Thanks for the heads up! I haven't even started integrating trio-websocket into my own application, so I think _you_ are the only real user right now. I am okay with requring Trio > 0.8.0 if you are.

**Comment by belm0** [comment]
SGTM
