### ISSUE TITLE
tests failing (OS X)

### ISSUE THREAD

**Issue by belm0** [HyperionGray/trio-websocket#43]
On master, about 10 tests are failing on port attribute access:
```
RuntimeError: Cannot get port because this server has more than 1 listeners.
```
also `test_wrap_server_stream()` appears to be blocking indefinitely on `client.send_message`

**Comment by mehaase** [comment]
I can confirm that 12 of 23 tests fail on OS X for me as well. The tests currently pass on Ubuntu 18.04. I will troubleshoot the failing tests and then set up a CI instance to test on multiple platforms.
