### ISSUE TITLE
use pipenv for development dependencies and running tests

### ISSUE THREAD

**Issue by belm0** [HyperionGray/trio-websocket#61]
e.g. see Pipfile and Makefile in https://github.com/requests/requests

**Comment by belm0** [comment]
https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/

virtualenvwrapper and pip-tools may be a better approach

**Comment by belm0** [comment]
Re. Sphinx, how about keeping extras in requirements-extra.txt instead of setup.py?  read docs must support it, e.g. trio does this.

**Comment by mehaase** [comment]
I'm trying out pip-tools this morning. I like it, but its author [recommends Pipenv instead](https://nvie.com/posts/better-package-management/):

>Note: While the principles outlined in this blog post still very much apply, your tool of choice these days should be Pipenv.

But PyPA still recommends pip-tools [as an alternative to Pipenv](https://packaging.python.org/tutorials/managing-dependencies/#installing-pipenv):

> If you find this particular approach to managing application dependencies isn’t working well for you or your use case, you may want to explore … pip-tools to build your own custom workflow from lower level pieces like pip-compile and pip-sync

Anyway… I have a working setup that I will commit in a few minutes.

**Comment by mehaase** [comment]
Closed via #78.
