### ISSUE TITLE
Migrate to travis-ci.**com**

### ISSUE THREAD

**Issue by mehaase** [HyperionGray/trio-websocket#91]
We are currently using travis-ci.**org**. I didn't realize when I set this up that Travis is in the process of moving open source repos from .org to .com. Moreover, the .com server supports "GitHub Apps", which looks like it would have better integration than the webhooks we're using right now. (Among other things, the webhooks currently build each PR that I push *twice*: once for the PR hook and once for the push hook.)

More info: https://docs.travis-ci.com/user/open-source-on-travis-ci-com/

**Comment by mehaase** [comment]
Ready to close this. This screenshot shows a recent PR is building correctly (building once, not twice).

![screenshot from 2019-01-15 10-05-09](https://user-images.githubusercontent.com/320904/51189094-50789780-18ad-11e9-8011-f124457454ce.png)

**Comment by belm0** [comment]
FYI I've just enabled builds for pull requests, as we had on travis-ci.org
